In [29]:
import glob
lst = glob.glob('*서울시*.xlsx')
print(len(lst))
lst

12

['2018년 04월 서울시 차량통행속도.xlsx',
 '2018년 05월 서울시 차량통행속도.xlsx',
 '2018년 06월 서울시 차량통행속도.xlsx',
 '2018년 07월 서울시 차량통행속도.xlsx',
 '2018년 08월 서울시 차량통행속도.xlsx',
 '2018년 09월 서울시 차량통행속도.xlsx',
 '2018년 10월 서울시 차량통행속도.xlsx',
 '2018년 11월 서울시 차량통행속도.xlsx',
 '2018년 12월 서울시 차량통행속도.xlsx',
 '2019년 01월 서울시 차량통행속도.xlsx',
 '2019년 02월 서울시 차량통행속도.xlsx',
 '2019년 03월 서울시 차량통행속도.xlsx']

In [22]:
import pandas as pd
car = pd.read_excel('2018년 04월 서울시 차량통행속도.xlsx')
car.drop(['시점명','종점명'],axis=1,inplace=True)
car = pd.melt(car, id_vars=car.columns[:10])
print(car.shape)
car.head()

(3530280, 12)

,일자,요일,도로명,링크아이디,방향,거리,차선수,기능유형구분,도심/외곽구분,권역구분,variable,value
0,20190301,금,4.19로,1080012200,상행,1179,1,보조간선도로,외곽,강북구,01시,44.60
1,20190301,금,4.19로,1080012800,상행,352,1,보조간선도로,외곽,강북구,01시,16.46
2,20190301,금,4.19로,1080012700,하행,354,2,보조간선도로,외곽,강북구,01시,27.55
3,20190301,금,4.19로,1080012100,하행,1190,2,보조간선도로,외곽,강북구,01시,47.88
4,20190301,금,가락로,1230024700,상행,844,1,기타도로,외곽,송파구,01시,27.57

In [34]:
from sklearn.preprocessing import LabelEncoder

lb_make = LabelEncoder()
car["요일"] = lb_make.fit_transform(car["요일"])
car["방향"] = lb_make.fit_transform(car["방향"])
car["기능유형구분"] = lb_make.fit_transform(car["기능유형구분"])
car["도심/외곽구분"] = lb_make.fit_transform(car["도심/외곽구분"])
car["권역구분"] = lb_make.fit_transform(car["권역구분"])
car["variable"] = lb_make.fit_transform(car["variable"])

car.head()

,일자,요일,도로명,링크아이디,방향,거리,차선수,기능유형구분,도심/외곽구분,권역구분,variable,value
0,20190301,0,4.19로,1080012200,0,1179,1,2,1,2,0,44.60
1,20190301,0,4.19로,1080012800,0,352,1,2,1,2,0,16.46
2,20190301,0,4.19로,1080012700,1,354,2,2,1,2,0,27.55
3,20190301,0,4.19로,1080012100,1,1190,2,2,1,2,0,47.88
4,20190301,0,가락로,1230024700,0,844,1,0,1,17,0,27.57

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score

y_target = car['value']
X_data = car.drop(['일자','도로명','value'],axis=1,inplace=False)

X_train , X_test , y_train , y_test = train_test_split(X_data , y_target ,test_size=0.3, random_state=156)

# Linear Regression OLS로 학습/예측/평가 수행. 
lr = LinearRegression()
lr.fit(X_train ,y_train )

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
y_preds = lr.predict(X_test)
mse = mean_squared_error(y_test, y_preds)
rmse = np.sqrt(mse)

print('MSE : {0:.3f} , RMSE : {1:.3F}'.format(mse , rmse))
print('R squared : {0:.3f}'.format(r2_score(y_test, y_preds)))